// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Record struct {
	ID         uuid.UUID
	DeviceID   string
	Type       string
	Amount     int32
	IsUploaded bool
	UploadedAt sql.NullInt64
	Ts         int64
	CreatedAt  int64
}
