// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateRecord(ctx context.Context, arg CreateRecordParams) (Record, error)
	GetUnuploadedRecords(ctx context.Context, limit int32) ([]Record, error)
	SetRecordIsUploaded(ctx context.Context, arg SetRecordIsUploadedParams) error
}

var _ Querier = (*Queries)(nil)
