// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Record struct {
	CreatedBy         uuid.NullUUID
	CreatedUserAgent  sql.NullString
	CreatedClientIp   sql.NullString
	Type              string
	StoreID           uuid.UUID
	RecordID          sql.NullString
	UserID            uuid.NullUUID
	DeviceID          sql.NullString
	FromOnlinePayment sql.NullString
	Amount            int32
	PointAmount       sql.NullInt32
	Ts                int64
	CreatedAt         int64
}

type Store struct {
	ID        uuid.UUID
	Name      string
	Address   string
	State     string
	Password  sql.NullString
	CreatedAt int64
}

type StoreDevice struct {
	StoreID     uuid.UUID
	DeviceID    string
	Name        string
	RealType    string
	DisplayType string
	State       string
	CreatedAt   int64
}

type StoreDevicesHistory struct {
	ChangedAt        int64
	ChangedType      string
	ChangedBy        uuid.NullUUID
	ChangedUserAgent sql.NullString
	ChangedClientIp  sql.NullString
	StoreID          uuid.UUID
	DeviceID         string
	Name             sql.NullString
	RealType         string
	DisplayType      string
	State            string
	CreatedAt        int64
	HistoryCreatedAt int64
}

type StoreUser struct {
	StoreID        uuid.UUID
	UserID         uuid.UUID
	Balance        int32
	Points         int32
	BalanceEarmark int32
	PointsEarmark  int32
	RoleID         int16
	State          string
	CreatedAt      int64
}

type StoreUsersHistory struct {
	ChangedAt        int64
	ChangedType      string
	ChangedBy        uuid.NullUUID
	ChangedUserAgent sql.NullString
	ChangedClientIp  sql.NullString
	StoreID          uuid.UUID
	UserID           uuid.UUID
	Balance          int32
	Points           int32
	BalanceEarmark   int32
	PointsEarmark    int32
	RoleID           int16
	State            string
	CreatedAt        int64
	HistoryCreatedAt int64
}

type StoresHistory struct {
	ChangedAt        int64
	ChangedType      string
	ChangedBy        uuid.NullUUID
	ChangedUserAgent sql.NullString
	ChangedClientIp  sql.NullString
	StoreID          uuid.UUID
	Name             string
	Address          string
	State            string
	Password         sql.NullString
	CreatedAt        int64
	HistoryCreatedAt int64
}

type Token struct {
	ID        uuid.UUID
	Type      string
	UserAgent string
	ClientIp  string
	IsBlocked bool
	UserID    uuid.UUID
	ExpiredAt int64
	IssuedAt  int64
	CreateAt  int64
}

type User struct {
	ID                 uuid.UUID
	PhoneNumber        string
	Name               string
	Password           string
	PasswordErrorCount int16
	PasswordChangedAt  sql.NullInt64
	RoleID             int16
	State              string
	CreatedAt          int64
}

type UsersHistory struct {
	ChangedAt          int64
	ChangedType        string
	ChangedBy          uuid.NullUUID
	ChangedUserAgent   sql.NullString
	ChangedClientIp    sql.NullString
	UserID             uuid.UUID
	PhoneNumber        string
	Name               string
	Password           string
	PasswordErrorCount int16
	PasswordChangedAt  sql.NullInt64
	RoleID             int16
	State              string
	CreatedAt          int64
	HistoryCreatedAt   int64
}

type VerCode struct {
	ID          uuid.UUID
	PhoneNumber string
	Code        string
	Type        string
	IsBlocked   bool
	RequestID   string
	ExpiredAt   int64
	CreateAt    int64
}
