// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: stores_history.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createStoreHistory = `-- name: CreateStoreHistory :one
INSERT INTO stores_history (changed_at, changed_type, changed_by, changed_user_agent, changed_client_ip, store_id, name, address, state, password, created_at)
SELECT $2, $3, $4, $5, $6, id, name, address, state, password, created_at
FROM stores AS s
WHERE s.id = $1
RETURNING changed_at, changed_type, changed_by, changed_user_agent, changed_client_ip, store_id, name, address, state, password, created_at, history_created_at
`

type CreateStoreHistoryParams struct {
	ID               uuid.UUID
	ChangedAt        int64
	ChangedType      string
	ChangedBy        uuid.NullUUID
	ChangedUserAgent sql.NullString
	ChangedClientIp  sql.NullString
}

func (q *Queries) CreateStoreHistory(ctx context.Context, arg CreateStoreHistoryParams) (StoresHistory, error) {
	row := q.db.QueryRowContext(ctx, createStoreHistory,
		arg.ID,
		arg.ChangedAt,
		arg.ChangedType,
		arg.ChangedBy,
		arg.ChangedUserAgent,
		arg.ChangedClientIp,
	)
	var i StoresHistory
	err := row.Scan(
		&i.ChangedAt,
		&i.ChangedType,
		&i.ChangedBy,
		&i.ChangedUserAgent,
		&i.ChangedClientIp,
		&i.StoreID,
		&i.Name,
		&i.Address,
		&i.State,
		&i.Password,
		&i.CreatedAt,
		&i.HistoryCreatedAt,
	)
	return i, err
}
